name: Linting

on:
  pull_request:
    branches: [ main, master ]

jobs:
  linting:
    name: Lua Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.1.0

