name: Build and Release to Itch.io

on:
  workflow_dispatch:
  push:
    tags:
      - '*'  # Runs on any tag push

jobs:
  build:
    name: Build .love File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

  release:
    name: Release to Itch.io
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: masterblaster-windows
          path: build/windows

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: masterblaster-mac
          path: build/mac

      - name: Deploy Windows Build to Itch.io
        uses: robpc/itchio-upload-action@v1
        with:
          path: build/windows/masterblaster-11.5-win64.zip
          project: ${{ secrets.ITCHIO_PROJECT }}
          channel: windows
          version: ${{ github.ref_name }}
          api-key: ${{ secrets.ITCHIO_API_KEY }}

      - name: Deploy macOS Build to Itch.io
        uses: robpc/itchio-upload-action@v1
        with:
          path: build/mac/masterblaster-mac.zip
          project: ${{ secrets.ITCHIO_PROJECT }}
          channel: mac
          version: ${{ github.ref_name }}
          api-key: ${{ secrets.ITCHIO_API_KEY }}
